### ISSUE TITLE
SEMSIM Profiles with value 0 in  phenodigm_score column when using --information-content flag

### ISSUE THREAD

**Issue by souzadevinicius** [monarch-initiative/semsimian#135]
Although the https://github.com/monarch-initiative/semsimian/issues/133 has resolved the Jaccard column values the  `phenodigm_score` column still has values as 0.

## Example **without IC** flag

| subject_id | subject_label                   | subject_source | object_id  | object_label                              | object_source | ancestor_id    | ancestor_label                              | ancestor_source | object_information_content | subject_information_content | ancestor_information_content | jaccard_similarity  | cosine_similarity | dice_similarity | phenodigm_score    |
|------------|---------------------------------|----------------|------------|-------------------------------------------|---------------|----------------|---------------------------------------------|-----------------|----------------------------|-----------------------------|------------------------------|---------------------|-------------------|-----------------|--------------------|
| HP:0020054 | Abnormal erythrocyte physiology | None           | MP:0002161 | abnormal fertility/fecundity              | None          | UPHENO:0002332 | abnormality of anatomical entity physiology | None            | None                       | None                        |            5.059610039003922 | 0.42857142857142855 | None              | None            | 1.4725502716139276 |
| HP:0020054 | Abnormal erythrocyte physiology | None           | MP:0011610 | abnormal primordial germ cell apoptosis   | None          | UPHENO:0085578 | abnormality of cell physiology              | None            | None                       | None                        |            7.733703155395898 |  0.4117647058823529 | None              | None            | 1.7845072163381734 |
| HP:0020054 | Abnormal erythrocyte physiology | None           | MP:0000230 | abnormal systemic arterial blood pressure | None          | UPHENO:0002332 | abnormality of anatomical entity physiology | None            | None                       | None                        |            5.059610039003922 | 0.41379310344827586 | None              | None            | 1.4469387479356148 |

## Example **with IC** flag

| subject_id | subject_label             | subject_source | object_id  | object_label                                             | object_source | ancestor_id | ancestor_label | ancestor_source | object_information_content | subject_information_content | ancestor_information_content | jaccard_similarity  | cosine_similarity | dice_similarity | phenodigm_score |
|------------|---------------------------|----------------|------------|----------------------------------------------------------|---------------|-------------|----------------|-----------------|----------------------------|-----------------------------|------------------------------|---------------------|-------------------|-----------------|-----------------|
| HP:0410253 | Myeloid maturation arrest | None           | MP:0013660 | abnormal bone marrow hematopoietic cell morphology       | None          | owl:Thing   | None           | None            | None                       | None                        |                          0.0 |  0.4528301886792453 | None              | None            |             0.0 |
| HP:0410253 | Myeloid maturation arrest | None           | MP:0011747 | myelofibrosis                                            | None          | owl:Thing   | None           | None            | None                       | None                        |                          0.0 |  0.4166666666666667 | None              | None            |             0.0 |
| HP:0410253 | Myeloid maturation arrest | None           | MP:0002398 | abnormal bone marrow cell morphology/development         | None          | owl:Thing   | None           | None            | None                       | None                        |                          0.0 | 0.40476190476190477 | None              | None            |             0.0 |

**Comment by justaddcoffee** [comment]
@souzadevinicius thanks for the update

Could you let us know what IC was used to generate the above result? 

Assuming you gave OAK/semsimian the IC map that contained IC for only MP and HP terms, I think this behavior above is correct. 

Taking for example the first row from second table above:

Get the common ancestor of these two terms:
```
(oaklib-py3.11) ~/PythonProject/ontology-access-kit  $ runoak -i sqlite:obo:phenio similarity -p i,p HP:0410253 @ MP:0013660
subject_id: HP:0410253
subject_label: Myeloid maturation arrest (HPO)
object_id: MP:0013660
object_label: abnormal bone marrow hematopoietic cell morphology (MPO)
ancestor_id: UPHENO:0004459
ancestor_label: abnormal hematopoietic system
[snip]
```

The common ancestor is `UPHENO:0004459`, which I think would not have an IC value. Semsimian currently assumes then that the IC of  `UPHENO:0004459` (and any/all terms that aren't in the IC file) are 0. Therefore the Resnik of `HP:0410253` and `MP:0013660` is 0.  So, the phenodigm score of Resnik = 0 and any Jaccard is 0:

`math.sqrt(sim.jaccard_similarity * 0)` # <--- always 0

**Comment by souzadevinicius** [comment]
> @souzadevinicius thanks for the update
> 
> Could you let us know what IC was used to generate the above result?
> 
> Assuming you gave OAK/semsimian the IC map that contained IC for only MP and HP terms, I think this behavior above is correct.
> 
> Taking for example the first row from second table above:
> 
> Get the common ancestor of these two terms:
> 
> ```
> (oaklib-py3.11) ~/PythonProject/ontology-access-kit  $ runoak -i sqlite:obo:phenio similarity -p i,p HP:0410253 @ MP:0013660
> subject_id: HP:0410253
> subject_label: Myeloid maturation arrest (HPO)
> object_id: MP:0013660
> object_label: abnormal bone marrow hematopoietic cell morphology (MPO)
> ancestor_id: UPHENO:0004459
> ancestor_label: abnormal hematopoietic system
> [snip]
> ```
> 
> The common ancestor is `UPHENO:0004459`, which I think would not have an IC value. Semsimian currently assumes then that the IC of `UPHENO:0004459` (and any/all terms that aren't in the IC file) are 0. Therefore the Resnik of `HP:0410253` and `MP:0013660` is 0. So, the phenodigm score of Resnik = 0 and any Jaccard is 0:
> 
> `math.sqrt(sim.jaccard_similarity * 0)` # <--- always 0

Yes, @justaddcoffee. You're right. I thought it might be an error because this mapping is 0 for every entry in the map. But this scenario doesn't apply to the HPxHP mapping file. Sorry for this mistake.

**Comment by justaddcoffee** [comment]
no problem @souzadevinicius, thanks for helping us test semsimian
