### ISSUE TITLE
Speed things up with rayon

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/semsimian#35]
In theory we can use rayon to do things like Jaccard and max ic in parallel using rayon, see for example [here](https://rust-lang-nursery.github.io/rust-cookbook/concurrency/parallel.html):

use rayon::prelude::*;

fn main() {
    let mut arr = [0, 7, 9, 11];
    arr.par_iter_mut().for_each(|p| *p -= 1);
    println!("{:?}", arr);
}

**Comment by justaddcoffee** [comment]
@hrshdhgd we did this right? Can we close this ticket?

**Comment by hrshdhgd** [comment]
Yes!
