### ISSUE TITLE
implement all_by_all_pairwise_similarity

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/semsimian#44]
Implement this in rust:

https://github.com/INCATools/ontology-access-kit/blob/ccfb6adf6e30573bcd199d626814b83bc9297028/src/oaklib/interfaces/semsim_interface.py#L343-L360

[note: new branch has min j/ic as params]

1. [x] implement in rust
2. [x] override this method in oak semsimian_implementation

Optional optimization: do a dual breadth or depth first down each graph, if any match doesn't meet threshold do not calculate further down (h/t @matentzn )

**Comment by hrshdhgd** [comment]
I agree!
