### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by leej3** [monarch-initiative/semsimian#52]
Thanks for sharing your work!

Could you add a license to this project please? Having no license can cause problems for downstream users... often they simply cannot use your project because of the legal implications of the software being unlicensed.

[Here](https://fossa.com/developers-guide-open-source-software-licenses) is a concise guide of some of the common choices available it.

**Comment by justaddcoffee** [comment]
Hi, yes, we will
do this asap - sorry for the oversight

**Comment by justaddcoffee** [comment]
closed by #53
