### ISSUE TITLE
Set up test coverage compatible with PyO3

### ISSUE THREAD

**Issue by caufieldjh** [monarch-initiative/semsimian#59]
@iQuxLE and I looked at https://github.com/cjermain/rust-python-coverage in an attempt to get test coverage calculation working in a way that works with PyO3 (`cargo-tarpaulin` consistently produced verbose errors seemingly related to PyO3).

Here's what worked (for me, at least):
```
$ cargo install cargo-llvm-cov
$ cargo llvm-cov show-env --export-prefix
$ cargo llvm-cov clean --workspace
$ cargo test
$ cargo llvm-cov --lcov --output-path coverage.lcov
$ sudo apt install lcov # if necessary, as this is what installs genhtml
$ genhtml -o output-dir coverage.lcov
```
This will run the rust tests and generate coverage reports in `output-dir`.
Including python tests should just require:
```
$ maturin develop
$ pytest tests --cov=foobar --cov-report xml
```

**Comment by justaddcoffee** [comment]
Excellent @caufieldjh! This worked like a charm for me too and it also seems to avoid that weird thing @iQuxLE was observing where lib.rs was counted as having several thousand lines of code (?) 

<img width="1405" alt="Screen Shot 2023-05-31 at 11 27 46 AM" src="https://github.com/monarch-initiative/semsimian/assets/150311/82b79deb-97e2-496f-862a-9baf7dec1cfa">

**Comment by caufieldjh** [comment]
Great, it works on M1 too then. Will try to incorporate into the workflow as part of #55

**Comment by caufieldjh** [comment]
Note that the pytest cov report needs `pip install pytest-cov`

**Comment by caufieldjh** [comment]
Done in #55
