### ISSUE TITLE
parallelize calculate_term_pairwise_information_content() for faster termset pairwise comparison

### ISSUE THREAD

**Issue by justaddcoffee** [monarch-initiative/semsimian#88]
[Here](https://github.com/monarch-initiative/semsimian/blob/8d11f4c4801c36e458373e3b81fdacffae0b560e/src/similarity.rs#L71) is where we are actually doing the termset comparisons. Looks like we are using `.iter()` here to loop through entity1 and entity2. 

This possibly is why calls to `termset_pairwise_similarity` is taking 8.2 s [here](https://github.com/INCATools/ontology-access-kit/blob/semsim-obj-create/notebooks/Semsimian/oak-semsimian-timing.ipynb)

We could possible speed this up with `rayon` by just changing these to `par_iters()`

I believe this would require `closure_map`, `ic_map`, and `predicates` to be immutable, not sure if this is the case

**Comment by hrshdhgd** [comment]
Duplicate #87

**Comment by justaddcoffee** [comment]
closed in favor of [Harshad's ticket](https://github.com/monarch-initiative/semsimian/issues/87)
